# Generated by Django 3.0.3 on 2020-02-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtest',
            name='related_problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ag_api.Problem'),
        ),
        migrations.AddField(
            model_name='problemtest',
            name='std_input',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='problemtest',
            name='std_output',
            field=models.TextField(max_length=65536, null=True),
        ),
    ]
