# Generated by Django 3.0.3 on 2020-04-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0003_tutorial_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialarticle',
            old_name='article',
            new_name='tutorial',
        ),
    ]
