# Generated by Django 3.0.3 on 2020-02-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0005_auto_20200209_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='interests',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='social_media_links',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
