# Generated by Django 3.0.3 on 2020-02-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0006_auto_20200209_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
