# Generated by Django 3.0.3 on 2020-02-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0007_remove_userdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
    ]
