# Generated by Django 3.0.3 on 2020-03-15 18:40

import ag_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ag_api', '0008_auto_20200209_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('interests', models.TextField(blank=True, max_length=1024)),
                ('profile_image', models.ImageField(blank=True, upload_to=ag_api.models.UserProfile.construct_path)),
                ('social_media_links', models.TextField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
