# Generated by Django 3.0.3 on 2020-03-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0011_problemsolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsolution',
            old_name='author',
            new_name='solution_author',
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='problem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ag_api.Problem'),
        ),
    ]
