# Generated by Django 3.0.3 on 2020-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0012_auto_20200319_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Perl', 'Perl'), ('Ruby', 'Ruby'), ('Haskell', 'Haskell'), ('Go', 'Go'), ('Erlang', 'Erlang'), ('C#', 'C#'), ('Bash', 'Bash'), ('PHP', 'PHP'), ('C', 'C'), ('Objective-C', 'Objective-C')], max_length=16, null=True),
        ),
    ]
