# Generated by Django 3.0.3 on 2020-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0016_auto_20200320_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
