# Generated by Django 3.0.3 on 2020-03-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0017_auto_20200320_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Perl', 'Perl'), ('Ruby', 'Ruby'), ('Haskell', 'Haskell'), ('Go', 'Go'), ('Erlang', 'Erlang'), ('C#', 'C#'), ('Bash', 'Bash'), ('PHP', 'PHP'), ('C', 'C'), ('Objective-C', 'Objective-C')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='problemsolution',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ag_api.Snippet'),
        ),
    ]
