# Generated by Django 3.0.3 on 2020-03-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ag_api', '0019_auto_20200320_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolution',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ag_api.Problem'),
        ),
        migrations.AlterField(
            model_name='problemsolution',
            name='solution_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(choices=[('c++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Perl', 'Perl'), ('Ruby', 'Ruby'), ('Haskell', 'Haskell'), ('Go', 'Go'), ('Erlang', 'Erlang'), ('C#', 'C#'), ('Bash', 'Bash'), ('PHP', 'PHP'), ('C', 'C'), ('Objective-C', 'Objective-C')], max_length=16, null=True),
        ),
    ]
