# Generated by Django 3.0.3 on 2020-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0020_auto_20200323_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('C++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, unique=True),
        ),
    ]
