# Generated by Django 3.0.3 on 2020-03-23 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0021_auto_20200323_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolution',
            name='score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(choices=[('C++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, null=True),
        ),
    ]
