# Generated by Django 3.0.3 on 2020-03-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0022_auto_20200323_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemsolution',
            old_name='solution_author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='problemsolution',
            name='snippet',
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='source_description',
            field=models.TextField(max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='source_text',
            field=models.TextField(max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='source_type',
            field=models.CharField(choices=[('C++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, null=True),
        ),
    ]
