# Generated by Django 3.0.3 on 2020-03-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0023_auto_20200324_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(choices=[('elementary', 'elementary'), ('easy', 'easy'), ('intermediate', 'intermediate'), ('upper intermediate', 'upper intermediate'), ('hard', 'hard')], default='easy'),
        ),
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.TextField(choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XII'), ('XII', 'XII')], null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='problemsolution',
            name='source_type',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='snippet_type',
            field=models.CharField(choices=[('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript'), ('perl', 'Perl'), ('ruby', 'Ruby'), ('haskell', 'Haskell'), ('go', 'Go'), ('erlang', 'Erlang'), ('c#', 'C#'), ('bash', 'Bash'), ('php', 'PHP'), ('c', 'C'), ('objective-c', 'Objective-C')], max_length=16, null=True),
        ),
    ]
