# Generated by Django 3.0.3 on 2020-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0024_auto_20200327_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.TextField(blank=True, choices=[('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XII'), ('XII', 'XII')], null=True),
        ),
    ]
