# Generated by Django 3.0.3 on 2020-03-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0025_auto_20200327_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
