# Generated by Django 3.0.3 on 2020-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0026_problem_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='date_posted',
            new_name='datetime_posted',
        ),
        migrations.RenameField(
            model_name='problemsolution',
            old_name='date_posted',
            new_name='datetime_posted',
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.TextField(choices=[('elementar', 'elementar'), ('usor', 'usor'), ('intermediar', 'intermediar'), ('dificil', 'dificil')], default='usor'),
        ),
    ]
