# Generated by Django 3.0.3 on 2020-03-27 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0027_auto_20200327_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='datetime_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 21, 26, 59, 675007)),
        ),
    ]
