# Generated by Django 3.0.3 on 2020-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0028_auto_20200327_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanations_and_indications',
            field=models.TextField(blank=True, max_length=65536),
        ),
        migrations.AlterField(
            model_name='problem',
            name='datetime_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
