# Generated by Django 3.0.3 on 2020-04-02 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0029_auto_20200402_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=65536)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
