# Generated by Django 3.0.3 on 2020-04-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0030_problemtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ag_api.ProblemTopic'),
        ),
    ]
