# Generated by Django 3.0.3 on 2020-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0032_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTaskChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
    ]
