# Generated by Django 3.0.3 on 2020-04-09 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0033_labtaskchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtaskchoices',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=256), null=True, size=None),
        ),
        migrations.AddField(
            model_name='labtaskchoices',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='labtaskchoices',
            name='single_response',
            field=models.BooleanField(default=True),
        ),
    ]
