# Generated by Django 3.0.3 on 2020-04-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ag_api', '0034_auto_20200409_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtaskchoices',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ag_api.Lab'),
        ),
    ]
